from tkinter import *
def add():
    ans=int(txt1.get())+int(txt2.get())
    txt3.insert(0,ans)
def post():
    ans=int(txt1.get())-int(txt2.get())
    txt3.insert(0,ans)
def new():
    ans=int(txt1.get())/int(txt2.get())
    txt3.insert(0,ans)
def app():
    ans=int(txt1.get())*int(txt2.get())
    txt3.insert(0,ans)
def now():
    txt1.delete(0,END)
    txt2.delete(0,END)
    txt3.delete(0,END)
root=Tk()
root.geometry("700x400")
root.title("Welcome")
root.config(bg="blue")
root.resizable(True,False)
root.iconbitmap("favicon.ico")
lbl=Label(text="Enter 1st numbr  :",background="blue", foreground="white")
lbl.place(x=100,y=100)
lbl2=Label(text="enter 2nd number :",background="blue",foreground="white")
lbl2.place(x=100,y=150)
lbl3=Label(text="answer :",background="blue",foreground="white")
lbl3.place(x=100,y=250)
txt1=Entry()
txt1.place(x=250,y=100)
txt2=Entry()
txt2.place(x=250,y=150)
btn=Button(text="SUM",command=add)
btn.place(x=250,y=200)
btn2=Button(text="SUB",command=post)
btn2.place(x=300,y=200)
btn3=Button(text="DIV",command=new)
btn3.place(x=350,y=200)
btn4=Button(text="MULTI",command=app)
btn4.place(x=400,y=200)
btn5=Button(text="CLEAR",command=now)
btn5.place(x=200,y=200)
txt3=Entry()
txt3.place(x=250,y=250)
root.mainloop()
